### ISSUE TITLE
System.NotSupportedException: 'The type 'System.Collections.Generic.List`

### ISSUE THREAD

**Issue by vstadn** [zcsizmadia/ZCS.DataContractResolver#27]
There is an issue while trying to deserialize List, IList - while IReadOnlyList still works. Any idea on how to cater for these cases? Thank you.

```
var objectTest = new FooModel()
{
    FooInner = new List<FooInnerModel>() 
    { 
        new FooInnerModel(){ FooInnerMember = 1}, new FooInnerModel() { FooInnerMember = 2 }
    }
};

var options = new System.Text.Json.JsonSerializerOptions()
{
    TypeInfoResolver = DataContractResolver.Default,
    DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
    PropertyNameCaseInsensitive = true,
    IncludeFields = true
};

var test = System.Text.Json.JsonSerializer.Serialize(objectTest, options);
var deserialized = System.Text.Json.JsonSerializer.Deserialize<FooModel>(test, options);

[DataContract]
public class FooModel
{
    [DataMember(Name = "foo_inner")]
    public List<FooInnerModel> FooInner { get; set; }
}

[DataContract]
public class FooInnerModel
{
    [DataMember(Name = "foo_inner_member")]
    public int FooInnerMember { get; set; }
}

```

**Comment by zcsizmadia** [comment]
Fixed #28 and published v1.0.2 version to nuget.org,

**Comment by vstadn** [comment]
unfortunately that won't work for types that require constructor params

if you change the List to array above instead you will get an exception on the latest version

**Comment by zcsizmadia** [comment]
#30 might be a better solution. Originally the resolver was based on DefaultJsonTypeInfoResolver which for some reason I decided not to use, however, that base resolver has support for  the default behaviour, Let me know if you have a  test case I should try to add before I release a new package.

**Comment by vstadn** [comment]
Sorry for not getting back to you earlier, initial tests are positive on my end. Let me spend some more time going through other test-cases and I will let you know if I run into any issues. Thanks again for the prompt fixes.

**Comment by zcsizmadia** [comment]
No worries at all. Thanks for your feedback and help!
